"""
gen_mediamtx_config.py
------------------------
Generates mediamtx.yml with one on-demand path per (camera, stream) in
_credentials.py's CAMERAS dict, all served on MediaMTX's single default
RTSP port -- this is what gives you one shared port for every camera and
stream, with each one only actually pulling from the camera while a viewer
is connected.

Usage:
    python gen_mediamtx_config.py > mediamtx.yml
    (or just run it -- it writes mediamtx.yml directly in this folder)

Then:
    mediamtx.exe mediamtx.yml

Paths come out as <camera>_main and <camera>_sub, e.g.:
    rtsp://127.0.0.1:8554/front_main
    rtsp://127.0.0.1:8554/front_sub
"""

import os
import sys

import _credentials as credentials

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
PYTHON = sys.executable
SCRIPT = os.path.join(SCRIPT_DIR, "xmeye_cloud_to_rtsp.py")


def win_safe(path):
    """MediaMTX's runOnDemand command parser treats backslash as a shell
    escape character even on Windows, which mangles ordinary Windows paths
    (C:\\Python\\python.exe becomes C:Pythonpython.exe -- every backslash
    silently eaten). Windows itself accepts forward slashes in paths just
    fine, so use those instead of fighting MediaMTX's parser."""
    return path.replace("\\", "/")


def main():
    cams = getattr(credentials, "CAMERAS", None)
    if not cams:
        sys.exit("_credentials.py has no CAMERAS dict defined -- add at least one camera first.")

    lines = [
        "# Generated by gen_mediamtx_config.py -- re-run it after editing CAMERAS",
        "# in _credentials.py rather than hand-editing the paths below.",
        "logLevel: info",
        "rtspAddress: :8554",
        "paths:",
    ]
    for name in cams:
        for stream, label in ((0, "main"), (1, "sub")):
            path_name = f"{name}_{label}"
            cmd = (
                f'{win_safe(PYTHON)} "{win_safe(SCRIPT)}" --camera {name} --stream {stream} '
                f'--protocol push --push-url rtsp://127.0.0.1:$RTSP_PORT/$MTX_PATH'
            )
            lines.append(f"  {path_name}:")
            lines.append(f"    runOnDemand: {cmd}")
            lines.append("    runOnDemandRestart: yes")
            lines.append("    runOnDemandStartTimeout: 30s")
            lines.append("    runOnDemandCloseAfter: 60s")

    content = "\n".join(lines) + "\n"
    out_path = os.path.join(SCRIPT_DIR, "mediamtx.yml")
    with open(out_path, "w") as f:
        f.write(content)
    print(f"[+] Wrote {out_path}")
    print("[+] Paths:")
    for name in cams:
        for label in ("main", "sub"):
            print(f"      rtsp://127.0.0.1:8554/{name}_{label}")


if __name__ == "__main__":
    main()